environment:
  qa:
    database:
      pymysql:
        db_name: transfer
        host: transfer-host-db
        port: 1234
        user: any
        password: 1234
    api:
      transfer_api: localhost:8080/qa-exam/transfer
